### ISSUE TITLE
App stops recording / site1

### ISSUE THREAD

**Issue by metroyeur** [voidtemp/OpenXStreamLoader#16]
Hello, i have encounter an issue about 2 weeks ago, i can no longer record one specific chat room on site1, i am able to record other chat room without any issue, is my ip address being blocked ? or is there a way to circumvent this ? thank you. 

for info, when chat room is active i hit START as usual, the app records for a few seconds then goes to "waiting" status, all this while the chat room is active...

**Comment by voidtemp** [comment]
right Click on task and check console output for errors.
May be HDD is full.
May be you selected video quality that is not supported by room. Check in
browser available vudeo resolutions.

**Comment by metroyeur** [comment]
Hi, thank for getting back.

So  i'm getting this error: "not playable streams found on this url"  / end of streamlink for windows with exitcode 1 

i have plenty of HDD space and always check on "BEST" for video quality, and it always worked, i can record other rooms with no issues so i think maybe my ip address is being blocked...

**Comment by voidtemp** [comment]
not playable streams found on this url

That's wierd. Is it public or private show? I had never tested it for
privates.

You can post room name on reddit, I'll check it out.

**Comment by metroyeur** [comment]
yes it's public... 

how can i find you on reddit  ?

**Comment by voidtemp** [comment]
Search for app name.

**Comment by metroyeur** [comment]
done ;)

**Comment by voidtemp** [comment]
Looks like your post got auto deleted. But I still can read it. Room is currently offline, I will check it later.

**Comment by metroyeur** [comment]
that's weird.. i can still see it...  but thanks anyways

**Comment by voidtemp** [comment]
No problems with recording.

**Comment by metroyeur** [comment]
yeah, i figured the user block me somehow, i can still watch the stream on a different browser but i just can't record...

**Comment by voidtemp** [comment]
There should not be difference between watching and recording. Try other
destination folder for output file.

**Comment by metroyeur** [comment]
ok will try that, thanks

**Comment by metroyeur** [comment]
hey there, i keep having the same issue, but no worries, i figured it's not the software as i'm still able to record other rooms, i got blocked by this user... oh well, not the end of the world, thanks anyways.

**Comment by voidtemp** [comment]
Anyway you still can record public shows as anonymous.

**Comment by metroyeur** [comment]
not sure about that, i think my IP is blocked, but i'll give it a try ;)
