### ISSUE TITLE
[Feature Request] Post-Processing and/or File Renaming

### ISSUE THREAD

**Issue by MisterX2000** [voidtemp/OpenXStreamLoader#18]
It would be nice to have a Post-Processing option, so that the `.ts` files can be converted to `.mp4` files, which are much smaller without re-encoding using FFmpeg.
Another (much simpler) option would be to change the extension when it's done, so an external script can batch convert the files in the folder. For example name the file `title.ts.part` and when it's done remove the `.part`, so the other script knows, it's done recording.

The external script could then look like this:
```batch
@echo off
cls
for %%i in (rec\*.ts) do (
	echo.
	echo Processing: %%i
	echo.
	ffmpeg -i "%%i" -c copy "done\%%~ni.mp4"
)
pause
```

**Comment by voidtemp** [comment]
Hello!

"are much smaller _without re-encoding_"
Sounds like a magic.
I've just tried your ffmpeg command line and 1.37Gb .ts was converted to 1.33Gb .mp4 (3% smaller).
So I would say it's only a _bit_ smaller.

I can suggest even more simpler option: different folders. Let application download to e.g. /RawTSFilesFolder/ and then convert new mp4 to somewhere else, then delete every processed file.

Sorry if I didn't understand your problem/solution.

**Comment by MisterX2000** [comment]
> I can suggest even more simpler option: different folders. Let application download to e.g. /RawTSFilesFolder/ and then convert new mp4 to somewhere else, then delete every processed file.

That's what I'm doing right now.
The Problem with that is, that there are files in the `/RawTSFilesFolder/` that are done and some that are still recording, but FFmpeg doesn't care if they are done recording, it converts every single File, because I want to execute the script perpetually.

**Comment by MisterX2000** [comment]
I kinda found another solution, by checking when the file was modified last.
https://gist.github.com/MisterX2000/11b02199132285f16092a1de07b41e4b

**Comment by voidtemp** [comment]
But I still wonder is it worth that 3%?

**Comment by MisterX2000** [comment]
I think so, because I have checked my Files and I save around 3-5% and if you have like 300 GB of captured data, you can save around 12 GB.
And .mp4 is just a more commonly used container, that has a greater support for devices.
But I've found a temporary solution that I've mention earlier that works for me.

The only thing that I might suggest is another feature, where files are automatically discarded if their recording time is under a certain threshold.
