### ISSUE TITLE
need more function =)

### ISSUE THREAD

**Issue by razor91111** [voidtemp/OpenXStreamLoader#2]
Please add a couple of things that will be very useful
1: Hide program system trey without close program
2: Remux the stream after the end of the recording, for example, in mp4 or mkv via ffmpeg

**Comment by voidtemp** [comment]
Hello!

Thanks for feedback.

1. In progress. Plus optional popup when fav model becomes online.
2. I'm not sure why is this needed) I'm watching .ts in MediaPlayerClassic with no problems. Also I have some remuxed to .mp4 streams and I had noticed that MPC spends few seconds to open them. While .ts is opened instantly. Maybe it's my local problem, idk.

**Comment by voidtemp** [comment]
"1" is now implemented in v0.3.
