### ISSUE TITLE
OFFLINE/ Failure to update online status

### ISSUE THREAD

**Issue by wyntresparkz** [voidtemp/OpenXStreamLoader#20]
as of today 01/22/21 all favorites are reading as offline and no longer updating their online status properly. Room images also fail to update.
This breaks the auto record function as well, as it's not updating the online status.

**Comment by voidtemp** [comment]
Yes, same is here.
This issue should be addressed as soon as possible.

**Comment by Rounlet** [comment]
A completely same issue here.
I hope this program will be improved soon. Because I'm using it really well. Please don't break my hope.

**Comment by voidtemp** [comment]
What was the idea of making this project open source? To give possibility for everyone to make changes to software themselves and maybe contribute (share improvements with others). And you're a bit breaking my hope into that.
I'm using this program myself too so yes I'll update it whenever I will have free time.

**Comment by voidtemp** [comment]
Please check v0.4 and please don't forget to close the issue if the problem was fixed.

**Comment by Rounlet** [comment]
I'm really sorry if what I said came as pressure. 
It's a great program, so I think it was wrong to express my sadness. 

Thank you for your quick improvement.

**Comment by wyntresparkz** [comment]
I apologize for the delay, 0.4 seems to have resolved the issue, thank you for coming off break to fix the issue. marking closed now.
