### ISSUE TITLE
Config corrupt and buggy program

### ISSUE THREAD

**Issue by xfisbest** [voidtemp/OpenXStreamLoader#21]
I got this issue 2 days back, i thought any virus or something attack my pc, but no it was openx itself, its config file got corrupted or idk what happened, it said cannot open config or something like that and later reset whole openxstream, i mean all favourites and loaded models were removed along with settings, i again had to do everything back, and now it is bugged, showing offline on even online and active rooms, (not private or ticket or group) public shows are also shown offline, and when someone go private and come back, it is also unable to detect back and start recording again. i think this needs an update. my all settings are default only record path is something else

**Comment by voidtemp** [comment]
Thanks for feedback.
"offline status" issue is of high priority.

**Comment by xfisbest** [comment]
I've tested fresh download of openx too, but the issue is in program itself, from my side there is no permissions issue or anything like that. I hope this get fixed soon 😄  as i have freed 150gbs for new streams ✌️
