### ISSUE TITLE
Error on CB recordings

### ISSUE THREAD

**Issue by dante0397** [voidtemp/OpenXStreamLoader#4]
![Qbn3UOI](https://user-images.githubusercontent.com/1333083/93973565-cb64a780-fd4a-11ea-9e05-333da0c59f99.png)
Is it normal that I'm always getting error since the last update?

**Comment by voidtemp** [comment]
Can you right click on a task and tell the console output?
Also try to open that link in browser, maybe your IP got banned.

**Comment by Erzfreund** [comment]
Had the same Problem. After starting "OpenXStreamLoader.exe" as Administrator it worked for me.

**Comment by voidtemp** [comment]
**Erzfreund**,
maybe you tried to save stream to some protected location like "C:\" or "C:\Program Files"?
Anyway it's usually a bad practice to run anything as Administrator.

**Comment by Erzfreund** [comment]
Thanks for your Information. I tried to start the recording of a stream without Administrator rights... and it worked too. 
Don't know what happend.

**Comment by voidtemp** [comment]
**Erzfreund**,
there is a ""View Streamlink output"" menu item if you right click on a task. It's better to start from there.
I'll add some better and verbose logging in the next release.

**Comment by voidtemp** [comment]
@everyone
In code there are only two places where `TaskState.StartProcessError` is set:
https://github.com/voidtemp/OpenXStreamLoader/blob/fa017cab9a8832bce81b62fb9edf0094920f6d0b/Task.cs#L167
and
https://github.com/voidtemp/OpenXStreamLoader/blob/fa017cab9a8832bce81b62fb9edf0094920f6d0b/Task.cs#L241

Both cases should be reflected in output message.
