### ISSUE TITLE
Question - Tranfering favorites when upgrading to new version

### ISSUE THREAD

**Issue by Mush-r00m** [voidtemp/OpenXStreamLoader#7]
Is it possible to transfer favorited models after upgrading to a newer version?

**Comment by voidtemp** [comment]
From INI to XML?
Sorry, but no. But you still can open INI file and reenter URLs again.
I must say using INI was a mistake.

**Comment by Mush-r00m** [comment]
Thanks for the reply. However since i follow hundreds of models, re entering that many urls all over again at once isnt very efficent. Would be much easier if they were all saved in a file that was transferable between versions.
